api/urls.py
from django.conf.urls import patterns, url
from api import views

urlpatterns = patterns('',
    url(r'^v1/intruders/list/$', views.intruder_list, name='intruder_list'),
    url(r'^v1/intruders/add/$', views.arduino_post, name='arduino_post'),
)

cms/urls.py
from django.conf.urls import patterns, url, include
from cms import views

urlpatterns = patterns('',
    url(r'^intruder/$', views.intruder_list, name='intruder_list'),
    url(r'^intruder/add/$', views.intruder_edit, name='intruder_add'),
    url(r'^intruder/mod/(?P<intruder_id>\d+)/$', views.intruder_edit, name='intruder_mod'),
    url(r'^intruder/del/(?P<intruder_id>\d+)/$', views.intruder_del, name='intruder_del'),
)

homesecurity/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'homesecurity.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^cms/', include('cms.urls', namespace='cms')),
    url(r'^api/', include('api.urls', namespace='api')),
)

api/models.py
from django.db import models

# Create your models here.

cms/models.py
from django.db import models
import datetime

# Create your models here.
class Intruder(models.Model):
    '''侵入者情報'''
    name = models.TextField('Intruder name', max_length=255, default='Intruder')
    timeStamp = models.DateTimeField('Intrusion time', auto_now=True)
    
    def __str__(self):
        return self.name

cms/forms.py
# -*-coding: utf-8 -*-
from django.forms import ModelForm
from cms.models import Intruder

class IntruderForm(ModelForm):
    class Meta:
        model = Intruder
        fields = ('name',)

api/views.py
from django.shortcuts import render
from collections import OrderedDict
from django.http import HttpResponse
from cms.models import Intruder
from cms.forms import IntruderForm
import json

# Create your views here.
def render_json_response(request, data, status=None):
    '''GETの結果'''
    json_str = json.dumps(data, ensure_ascii=False, indent=2)
    callback = request.GET.get('callback')
    if not callback:
        callback = request.REQUEST.get('callback')
    if callback:
        json_str = "%s(%s)" % (callback, json_str)
        response = HttpResponse(json_str, content_type='application/javascript; charset=UTF-8'
                                , status=status)
    else:
        response = HttpResponse(json_str, content_type='application/json; charset=UTF-8'
                                , status=status)
    return response

def intruder_list(request):
    '''侵入者情報を返す'''
    intruders = [];
    for intruder in Intruder.objects.all().order_by('id'):
        
        intruder_dict = OrderedDict([
                                     ('id', intruder.id),
                                     ('name', intruder.name),
                                     ('timeStamp', intruder.timeStamp.isoformat())
                                     ])
        intruders.append(intruder_dict)
        
    data = OrderedDict([('intruders', intruders)])
    return render_json_response(request, data)

def arduino_post(request):
    intruder = Intruder()
    
    if request.method=='POST':
        form = IntruderForm(request.POST, instance=intruder)
        if form.is_valid():
            intruder = form.save(commit=False)
            intruder.save()
            data = "OK"
        else:
            data="error"
    else:
        form = IntruderForm(instance=intruder)
    
    return render_json_response(request, data)
    
    

cms/views.py
from django.shortcuts import render, render_to_response, redirect,\
    get_object_or_404
from django.http.response import HttpResponse
from django.template.context import RequestContext
from cms.models import Intruder
from cms.forms import IntruderForm

# Create your views here.
def intruder_list(request):
    #return HttpResponse(u'侵入者情報')
    intruders = Intruder.objects.all().order_by('id')
    return render_to_response('cms/intruder_list.html',
                              {'intruders': intruders},
                              context_instance=RequestContext(request))
    
def intruder_edit(request, intruder_id=None):
    #return HttpResponse(u'侵入者の編集')
    
    if intruder_id:
        intruder = get_object_or_404(Intruder, pk=intruder_id)
    else:
        intruder = Intruder()
    
    if request.method=='POST':
        form = IntruderForm(request.POST, instance=intruder)
        if form.is_valid():
            intruder = form.save(commit=False)
            intruder.save()
            return redirect('cms:intruder_list')
    else:
        form = IntruderForm(instance=intruder)
        
    return render_to_response('cms/intruder_edit.html',
                              dict(form=form, intruder_id=intruder.id),
                              context_instance=RequestContext(request))
    
def intruder_del(request, intruder_id):
    #return HttpResponse(u'侵入者の削除')
    intruder = get_object_or_404(Intruder, pk=intruder_id)
    intruder.delete()
    return redirect('cms:intruder_list')
    

cms/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}IntruderList{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extrahead %}{% endblock %}
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
</body>
</html>

cms/templates/cms/intruder_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}IntruderEdit{% endblock title %}

{% block content %}
	<h3 class="page-header">Intruder edit</h3>
	{% if book_id %}
	<form action="{% url 'cms:intruder_mod' intruder_id=intruder_id %}" method="post" class="form-horizontal" role="form">
	{% else %}
	<form action="{% url 'cms:intruder_add' %} " method="post" class="form-horizontal" role="form">
	{% endif %}
		{% csrf_token %}
		{{ form|bootstrap_horizontal }}
		<div class="form-group">
			<div class="col-offset-2 col-sm-10">
				<button type="submit" class="btn btn-primary">Send</button>
			</div>
		</div>
	</form>
	<a href="{% url 'cms:intruder_list' %}" class="btn btn-default">Back</a>
{% endblock content %}

cms/templates/cms/intruder_list.html
{% extends "base.html" %}
{% block title %}IntruderList{% endblock title %}

{% block extrahead %}
<style>
	table {
		margin-top: 8px;
	}
</style>
{% endblock extrahead%}

{% block content %}
	<h3 class="page-header">Intruder's list</h3>
	<a href="{% url 'cms:intruder_add' %}" class="btn btn-default">Add</a>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>Intruder list</tr>
		</thead>
		<tbody>
			{% for intruder in intruders %}
			<tr>
				<td>{{ intruder.name }}</td>
				<td>{{ intruder.timeStamp }}</td>
				<td>
					<a href="{% url 'cms:intruder_mod' intruder_id=intruder.id %}" class="btn btn-default">Modify</a>
					<a href="{% url 'cms:intruder_del' intruder_id=intruder.id %}" class="btn btn-default">Delete</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock content %}